---
title: "Recap PCA-based motif analysis"
author: "Izaskun Mallona"
output:
  html_document:
    keep_md: false
    toc: true
    toc_float: true
    toc_depth: 4
params:
  seed: 11

---
    
```{r settings, include=FALSE}

library(knitr)
## library(devtools)
library(reshape2)
## library(lattice)
library(pheatmap)
## library(seqLogo)
## library(margins)
## library(data.table)
library(ggplot2)
## library(ggfortify)
## library(ggseqlogo)
## library(gridExtra)
library(MOFA)

TASK <- "cg_context"
HOME <- '/home/imallona'
WD <-  file.path(HOME, 'mnt', 'nfs', TASK)
DATA <- file.path(WD, 'feb_2019')

MIN_DEPTH <- 10

beta2m <- function(beta) {
    m <- log2(beta/(1 - beta))
    return(m)
}

m2beta <- function(m) {
    beta <- 2^m/(2^m + 1)
    return(beta)
}

opts_chunk$set(fig.width = 12,
               fig.height = 12,
               fig.path = file.path(WD, TASK, 'RmdFigs'),
               output.dir = WD,
               root.dir = WD,
               cache = TRUE,
               include = TRUE,
               cache.lazy = FALSE,
               warning = TRUE,
               message = TRUE)

dir.create(file.path(WD, TASK))

```

# Datasets load


```{r dictionaries}
## dictionaries of the whole set of motifs
nucl <- c('T', 'C', 'G', 'A')

mdict <- list('cg' = NULL, 'ch' = NULL)
mdict$cg <- apply(expand.grid('1' = nucl, '2' = nucl, '3' = nucl,
                              '4' = 'C',  '5' = 'G',
                              '6' = nucl, '7' = nucl, '8' = nucl ),
                  1,
                  function(x) paste(x, collapse = ''))



mdict$ch <- apply(expand.grid('1' = nucl, '2' = nucl, '3' = nucl,
                              '4' = 'C',  '5' = c('A', 'T', 'C'),
                              '6' = nucl, '7' = nucl, '8' = nucl),
                  1,
                  function(x) paste(x, collapse = ''))


for (item in names(mdict)) {
    fd <- mdict[[item]]
    fd <- sort(as.character(fd))
    fd <- data.frame(motif = fd, count = 0)
    rownames(fd) <- fd$motif
    mdict[[item]] <- fd
    rm(fd)
}


```


```{r dataload}
sources <- list.files(file.path(DATA), recursive = FALSE)

d <- list()
for (batch in sources) {

    curr <- list(cg = data.frame(motif = mdict$cg$motif, row.names = 1),
                 ch = data.frame(motif = mdict$ch$motif, row.names = 1))

    fns <- list.files(file.path(DATA, batch, 'discretized'))
    tryCatch({
        for (context in c('cg', 'ch')) {
            for (thres in c('000', '010', '020', '030', '040', '050', '060', '070',
                            '080', '090', '100')) {
                
                fn_match <- grep(sprintf(".*%s.*%s.*%s.*", batch, context, thres), fns, value = TRUE)

                fn_match <- file.path(DATA, batch, 'discretized', fn_match)
                
                if (file.exists(fn_match)) {
                    fd <- read.table(fn_match, col.names = c('count', 'motif'),
                                     stringsAsFactors = FALSE)

                    ## removing Ns and short motifs
                    rownames(fd) <- fd$motif
                    fd <- fd[grep('N', fd$motif, invert = TRUE),]
                    fd <- fd[nchar(fd$motif) == 8,]
                    fd <- fd[sort(fd$motif),]

                    ## filling with zeroes the motifs that are not present

                    mis <- setdiff(rownames(mdict[[context]]), rownames(fd))
                    fd <- rbind(fd, mdict[[context]][mis,])
                    ## lexicographical sorting
                    fd <- fd[order(as.character(fd$motif)),]
                    
                    
                    
                } else {
                    ## probably is missing due to the fact no motif is methylated
                    fd <- mdict[[context]]
                }

                stopifnot(nrow(fd) == nrow(mdict[[context]]))
                curr[[context]][,thres] <- fd$count
            }
        }
        
        d[[batch]] <- curr
    }, error = function(x) print(batch))
}

```


## Methylation statuses as views


Mind might make sense having methylation statuses as views, columns are samples, rows as motifs (observations).


```{r rotated}
## r <- setNames(as.character(mdict$cg$motif), rep(NA, length(mdict$cg$motif)))

views <- list()
context <- 'cg'

for (status in c('000', '010', '020', '030', '040', '050',
                 '060', '070', '080', '090', '100')) {

    views[[status]] <- list(thres = mdict[[context]]$motif)
    for (batch in names(d)) {
        views[[status]][[batch]] <- d[[batch]][[context]][,status]
    }
    views[[status]] <- do.call(cbind.data.frame, views[[status]])
    rownames(views[[status]]) <- views[[status]][,1]
    views[[status]] <- views[[status]][,-1]
}
    
```



```{r prevariance_filtering}
for (assay in names(views)){
    vars <- apply(as.matrix(views[[assay]]),1, function(x) var(x,na.rm = TRUE))
    selected <- vars != 0 & !is.na(vars)
    views[[assay]] <- views[[assay]][selected,]
    rm(vars, selected)
}

```



```{r mofa_pre}
MOFAobject <- createMOFAobject(views)
plotTilesData(MOFAobject)


DataOptions <- getDefaultDataOptions()
DataOptions$removeIncompleteSamples <- TRUE
DataOptions

ModelOptions <- getDefaultModelOptions(MOFAobject)

## ## ModelOptions$numFactors <- 20
## ModelOptions <- list(likelihood = c('gaussian', 'bernoulli', 'gaussian', 'gaussian'),
##                      numFactors = 50,
                     sparsity = TRUE)
ModelOptions

TrainOptions <- getDefaultTrainOptions()
## Automatically drop factors that explain less than 2% of variance in all omics
TrainOptions$DropFactorThreshold <- 0.02

TrainOptions$seed <- 1
TrainOptions

MOFAobject <- prepareMOFA(
    MOFAobject, 
    DataOptions = DataOptions,
    ModelOptions = ModelOptions,
    TrainOptions = TrainOptions)
```


```{r runmofa}
MOFAobject <- runMOFA(MOFAobject, outfile = file.path(WD, 'mofa.out'))

```

```{r mofa_vis}

r2 <- calculateVarianceExplained(MOFAobject)
r2$R2Total

head(r2$R2PerFactor)

plotVarianceExplained(MOFAobject)

for (status in names(views)) {
    plotWeightsHeatmap(
        MOFAobject, 
        view = status, 
        factors = 1:5,
        show_colnames = FALSE)

    plotWeights(
        MOFAobject, 
        view = status, 
        factor = 1, 
        nfeatures = 5)

    plotDataHeatmap(
        MOFAobject, 
        view = status, 
        factor = 1, 
        features = 20, 
        show_rownames = TRUE)
}

```




# Motifs as views

Motifs are views, columns are samples, rows are methylation statuses (observations)

CG only first

@todo vectorize this

```{r rotated2, eval = FALSE}
## r <- setNames(as.character(mdict$cg$motif), rep(NA, length(mdict$cg$motif)))

views <- list()
context <- 'cg'

for (motif in as.character(mdict[[context]]$motif)){
    views[[motif]] <- list(thres = as.numeric(c('000', '010', '020', '030', '040', '050',
                                                '060', '070', '080', '090', '100')))
    for (batch in names(d)) {
        views[[motif]][[batch]] <- d[[batch]][[context]][motif,]
    }

    views[[motif]] <- t(do.call(rbind.data.frame, views[[motif]]))[,-1]
                                                                  
}
    
```
